
version: '3.5'
services:
  web-app:
      container_name: thesis
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '8080:8080'
      env_file:
        - .env
      environment:
        - NODE_ENV=production
        - THESIS_API_URL=http://127.0.0.1:5000